name: Deploy App
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SSH Exec
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: |
          # Start SSH agent and add GitHub SSH key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/git_id_rsa

          # Go to project directory and pull latest code
          cd ${{ secrets.PATH }}
          git pull

          # Set up NVM environment and use Node.js v22
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm use 22

          # Install dependencies and build the app
          npm install
          npm run build

          # Restart the app with pm2 (assumes pm2 is globally installed)
          pm2 restart thelonelylands --silent
