name: Deploy App
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SSH Exec
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: |
          eval `ssh-agent -s`
          ssh-add ~/.ssh/git_id_rsa
          cd ${{ secrets.PATH}} 
          git pull
          ${{ NODE }}/node ${{ NODE }}/npm install
          ${{ NODE }}/node ${{ NODE }}/npm run build
          ${{ NODE }}/node ${{ NODE }}/pm2 restart thelonelylands
